"""empty message

Revision ID: 0961d1af2403
Revises: d3a3458ae304
Create Date: 2021-12-11 17:37:19.396266

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0961d1af2403'
down_revision = 'd3a3458ae304'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('t_users', sa.Column('age', sa.SmallInteger(), nullable=True))
    op.add_column('t_users', sa.Column('gender', sa.Enum('woman', 'man'), nullable=True))
    op.add_column('t_users', sa.Column('addr', sa.String(length=256), nullable=True))
    op.add_column('t_users', sa.Column('mobile', sa.Integer(), nullable=True))
    op.add_column('t_users', sa.Column('create_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('t_users', 'create_time')
    op.drop_column('t_users', 'mobile')
    op.drop_column('t_users', 'addr')
    op.drop_column('t_users', 'gender')
    op.drop_column('t_users', 'age')
    # ### end Alembic commands ###
