"""empty message

Revision ID: 7dff6a8ad3bc
Revises: 0961d1af2403
Create Date: 2021-12-11 17:39:03.981746

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7dff6a8ad3bc'
down_revision = '0961d1af2403'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('t_users')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('t_users',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('age', mysql.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('gender', mysql.ENUM('woman', 'man'), nullable=True),
    sa.Column('addr', mysql.VARCHAR(length=256), nullable=True),
    sa.Column('mobile', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('create_time', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
