"""empty message

Revision ID: ab82325c5b7c
Revises: 5071b4e36794
Create Date: 2021-12-13 15:38:18.733600

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ab82325c5b7c'
down_revision = '5071b4e36794'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('t_users', 'gender')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('t_users', sa.Column('gender', mysql.ENUM('woman', 'man', charset='utf8', collation='utf8_general_ci'), server_default=sa.text("'man'"), nullable=True))
    # ### end Alembic commands ###
