"""empty message

Revision ID: adfcbd066a10
Revises: ab82325c5b7c
Create Date: 2021-12-13 15:38:39.868053

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'adfcbd066a10'
down_revision = 'ab82325c5b7c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('t_users', sa.Column('gender', sa.Enum('1', '2'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('t_users', 'gender')
    # ### end Alembic commands ###
