"""empty message

Revision ID: bd3d70f0a6b1
Revises: adfcbd066a10
Create Date: 2021-12-13 15:44:01.172541

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bd3d70f0a6b1'
down_revision = 'adfcbd066a10'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('t_users', 'mobile')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('t_users', sa.Column('mobile', mysql.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
