"""empty message

Revision ID: d860b1d1f0fa
Revises: bd3d70f0a6b1
Create Date: 2021-12-13 15:44:10.491606

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd860b1d1f0fa'
down_revision = 'bd3d70f0a6b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('t_users', sa.Column('mobile', sa.String(length=11), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('t_users', 'mobile')
    # ### end Alembic commands ###
